services:
  - type: web
    name: flfp-data-explorer
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:server -b 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.13
